config/routes.rb
Checklists::Application.routes.draw do
  get 'welcome/index'

  resource :sessions, only: [:create, :new, :destroy]

  resource :users

  resources :checklists do
    resources :items
  end

  get 'my_checklists' => 'checklists#my_checklists', as: 'my_checklists'
  post 'checklists/:id/add' => 'checklists#add_checklist', as: 'add_checklist'

  root 'welcome#index'
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3 }

  belongs_to :author, class_name: User
  has_many :items, dependent: :destroy
  has_and_belongs_to_many :users, dependent: :destroy

  def can_be_edited_by?(user)
    user == self.author
  end

  def can_be_deleted_by?(user)
    user == self.author
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :text, presence: true

  belongs_to :checklist

  def can_be_edited_by?(user)
    user == self.checklist.author
  end

  def can_be_deleted_by?(user)
    user == self.checklist.author
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: true, length: {minimum: 3}, uniqueness: true
  validates :password_digest, :session_token, presence: true

  after_initialize :ensure_session_token

  has_and_belongs_to_many :checklists, dependent: :destroy

  has_many(
      :authored_checklists,
      class_name: Checklist,
      foreign_key: :author_id,
      primary_key: :id,
      dependent: :destroy
  )

  def self.find_by_credentials(username, password)
    user = self.find_by_username(username)
    return user && user.valid_password?(password) ? user : nil
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def can_edit?(resource)
    resource.can_be_deleted_by?(self)
  end

  def can_delete?(resource)
    resource.can_be_deleted_by?(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :signed_in?, :current_user

  private

  def sign_in(user)
    session[:session_token] = user.reset_token!
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_out
    current_user.reset_token!
    session[:session_token] = nil
  end

  def require_sign_in!
    redirect_to new_sessions_url unless signed_in?
  end

end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_filter :require_sign_in!, except: [:index, :show]

  def my_checklists
    @checklists = current_user.checklists
    flash.now[:my_checklists] = true
    render :index
  end

  def add_checklist
    @checklist = Checklist.find(params[:id])
    current_user.checklists << @checklist
    redirect_to @checklist
  end

  def create
    @checklist = Checklist.new(checklist_params)
    @checklist.author = current_user
    if @checklist.save
      redirect_to @checklist
    else
      render 'new'
    end
  end

  def new
    @checklist = Checklist.new
  end

  def show
    @checklist = Checklist.find(params[:id])
  end

  def index
    @checklists = Checklist.all
  end

  def edit
    @checklist = Checklist.find(params[:id])
  end

  def update
    @checklist = Checklist.find(params[:id])

    raise Exceptions::SecurityTransgression unless current_user.can_edit?(@checklist)

    @checklist.update(params[:checklist].permit(:title, :text))

    if @checklist.save
      redirect_to @checklist
    else
      render 'edit'
    end
  end

  def destroy
    @checklist = Checklist.find(params[:id])

    raise Exceptions::SecurityTransgression unless current_user.can_delete?(@checklist)

    @checklist.destroy
    redirect_to checklists_path
  end

  private

  def checklist_params
    params.require(:checklist).permit(:title, :text)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @checklist = Checklist.find(params[:checklist_id])
    @item = @checklist.items.create(item_params)
    redirect_to checklist_path(@checklist)
  end

  def destroy
    @checklist = Checklist.find(params[:checklist_id])
    @item = @checklist.items.find(params[:id])

    raise Exceptions::SecurityTransgression unless current_user.can_delete?(@item)

    @item.destroy
    redirect_to checklist_path(@checklist)
  end

  def item_params
    params.require(:item).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(session_params[:username], session_params[:password])
    if user
      sign_in(user)
      redirect_to welcome_index_path
    else
      flash.now[:errors] = 'Incorrect username/password combination'
      render :new
    end
  end

  def new
  end

  def destroy
    sign_out
    redirect_to new_sessions_url
  end

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_sign_in!, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      sign_in(@user)
      redirect_to welcome_index_path
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/checklists/_form.html.erb
<%= form_for :checklist, url: checklists_path do |f| %>
    <% if @checklist.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@checklist.errors.count, "error") %> prohibited
            this checklist from being saved:</h2>
          <ul>
            <% @checklist.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/checklists/edit.html.erb
<h1>Editing checklist</h1>

<%= render 'form' %>

<%= link_to 'Back', checklist_path %>

app/views/checklists/index.html.erb
<h1><% if flash[:my_checklists] %>My<% else %>All<% end %> checklists</h1>

<%= link_to 'New checklist', new_checklist_path %>
<br>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @checklists.each do |checklist| %>
      <tr>
        <td><%= checklist.title %></td>
        <td><%= checklist.text %></td>
        <td><%= link_to 'Show', checklist %></td>

        <% if current_user.can_edit?(checklist) %>
          <td><%= link_to 'Edit', edit_checklist_path(checklist) %></td>
        <% end %>

        <% if current_user.can_delete?(checklist) %>
          <td><%= link_to 'Destroy', checklist_path(checklist), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

        <% if !current_user.checklists.include?(checklist) %>
          <td><%= button_to 'Add', add_checklist_path(checklist) %></td>
        <% end %>

      </tr>
  <% end %>

</table>
<br>
<%= link_to 'Back', welcome_index_path %>

app/views/checklists/new.html.erb
<h1>New Checklist</h1>

<% if @checklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checklist.errors.count, "error") %> prohibited
        this post from being saved:</h2>
      <ul>
        <% @checklist.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', checklists_path %>

app/views/checklists/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @checklist.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @checklist.text %>
</p>

<h2>Items</h2>
<%= render @checklist.items %>

<h2>Add an item:</h2>
<%= render 'items/form' %>

<%= link_to 'Back', checklists_path %>
| <%= link_to 'Edit', edit_checklist_path(@checklist) %>

app/views/items/_form.html.erb
<%= form_for([@checklist, @checklist.items.build]) do |f| %>
    <p>
      <%= f.label :text %><br />
      <%= f.text_area :text %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/items/_item.html.erb
<p>
  <%= item.text %>
</p>

<% if current_user.can_delete?(item) %>
  <p>
    <%= link_to 'Delete Item', [item.checklist, item],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Checklists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
    <li class="nav-button" id="logout">
      <%= button_to "Log out",
                    sessions_url,
                    method: :delete,
                    class: "log-out" %>
    </li>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>
    <p>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to "My Checklists", my_checklists_path %>

<%= link_to "Browse Checklists", controller: "checklists" %>